name: Grab thumbnails

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests tqdm

      - name: Grab thumbnails
        run: |
          python - <<'PY'
          import os, re, time, json, pathlib, urllib.parse
          import requests
          from tqdm import tqdm

          REPO = os.getenv("GITHUB_REPOSITORY")
          BRANCH = os.getenv("GITHUB_REF_NAME") or "main"

          SRC = "all_fishes (4).lua"   # nama file kamu persis
          OUT_DIR = pathlib.Path("fish_png")
          OUT_DIR.mkdir(exist_ok=True)

          # Baca file sumber
          with open(SRC, "r", encoding="utf-8", errors="ignore") as f:
              data = f.read()

          # Regex sederhana untuk ambil Name & Icon (roblox asset id)
          # Kita kumpulkan berpasangan berdasarkan urutan kemunculan
          name_pat = re.compile(r'Name\s*=\s*"([^"]+)"')
          icon_pat = re.compile(r'Icon\s*=\s*"rbxassetid://(\d+)"')

          names = name_pat.findall(data)
          icons = icon_pat.findall(data)

          # Sinkronkan aman (kalau jumlah beda, pakai per-blok)
          # Fallback parser per-blok agar lebih andal:
          entries = []
          block_pat = re.compile(r'\{[^{}]*Name\s*=\s*"([^"]+)"[^{}]*Icon\s*=\s*"rbxassetid://(\d+)"[^{}]*\}', re.S)
          for nm, aid in block_pat.findall(data):
              entries.append((nm.strip(), aid.strip()))

          # Jika block parser kosong, fallback ke zip(names, icons)
          if not entries:
              entries = list(zip(names, icons))

          # Hilangkan duplikat sambil jaga urutan
          seen = set()
          dedup = []
          for nm, aid in entries:
              key = (nm.lower().strip(), aid)
              if key not in seen:
                  seen.add(key)
                  dedup.append((nm, aid))

          print(f"Found {len(dedup)} fish entries with icon ids.")

          # Download thumbnails
          MAP = {}  # name -> raw URL PNG di repo ini
          sess = requests.Session()

          for nm, aid in tqdm(dedup, ncols=80):
              # URL Roblox thumbnail
              thumb_url = f"https://www.roblox.com/asset-thumbnail/image?assetId={aid}&width=512&height=512&format=png"
              # Nama file aman
              safe = re.sub(r'[^A-Za-z0-9_.-]+', '_', nm.strip())
              png_path = OUT_DIR / f"{safe}.png"

              # Download kalau belum ada / kosong
              if not png_path.exists() or png_path.stat().st_size < 1000:
                  try:
                      r = sess.get(thumb_url, timeout=20)
                      r.raise_for_status()
                      with open(png_path, "wb") as w:
                          w.write(r.content)
                      time.sleep(0.35)  # throttle biar aman
                  except Exception as e:
                      print(f"[WARN] Failed {nm} ({aid}): {e}")
                      continue

              # Buat raw URL untuk embed Discord (PNG akan berada di repo)
              # Format: https://raw.githubusercontent.com/<user>/<repo>/<branch>/fish_png/<file>.png
              file_raw = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}/fish_png/{urllib.parse.quote(png_path.name)}"
              MAP[nm] = {
                  "assetId": aid,
                  "file": str(png_path).replace("\\","/"),
                  "raw": file_raw
              }

          # Tulis map JSON
          with open("fish_png_map.json", "w", encoding="utf-8") as w:
              json.dump(MAP, w, ensure_ascii=False, indent=2)

          print(f"Saved {len(MAP)} thumbnails → fish_png/, and fish_png_map.json")
          PY

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add fish_png/*.png fish_png_map.json || true
          # Commit hanya jika ada perubahan
          if ! git diff --cached --quiet; then
            git commit -m "chore: grab Roblox fish thumbnails & map"
            git push
          else
            echo "No changes to commit."
          fi
