name: Grab thumbnails

on:
  workflow_dispatch: {}

permissions:
  contents: write   # penting: biar bisa push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm

      - name: Grab thumbnails
        run: |
          python - <<'PY'
          import os, re, json, requests, time
          from tqdm import tqdm

          OUT_DIR = "thumbnails"
          os.makedirs(OUT_DIR, exist_ok=True)

          # file lua kamu (ganti kalau beda)
          LUA_URL = "https://raw.githubusercontent.com/deathstrats/Ketikamimpimu/main/all_fishes%20(4).lua"

          print("Download lua ...")
          text = requests.get(LUA_URL, timeout=60).text

          # ambil Icon dan Name
          items = []
          block = {}
          for line in text.splitlines():
            m_icon = re.search(r'Icon\s*=\s*"rbxassetid://(\d+)"', line)
            m_name = re.search(r'Name\s*=\s*"([^"]+)"', line)
            if m_icon: block["icon"]=m_icon.group(1)
            if m_name: block["name"]=m_name.group(1)
            if "}" in line and block.get("icon") and block.get("name"):
              items.append(block); block = {}

          print(f"Found {len(items)} entries")

          def norm(name:str)->str:
            s = name.strip().lower()
            s = re.sub(r'[^a-z0-9]+','_',s).strip('_')
            return s or "unknown"

          def thumb_url(asset_id:str)->str:
            return f"https://www.roblox.com/asset-thumbnail/image?assetId={asset_id}&width=512&height=512&format=png"

          ok, fail = 0,0
          for it in tqdm(items):
            url = thumb_url(it["icon"])
            out = os.path.join(OUT_DIR, f"{norm(it['name'])}.png")
            try:
              r = requests.get(url, timeout=60)
              if r.status_code==200 and r.content:
                with open(out,"wb") as f: f.write(r.content)
                ok+=1
              else:
                fail+=1
            except Exception as e:
              fail+=1
          print(f"OK={ok} FAIL={fail}")
          PY

      - name: Commit PNGs
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add thumbnails/*.png
            git commit -m "Add/Update fish thumbnails (auto)"
            git push
          else
            echo "No changes to commit."
          fi
