name: Grab thumbnails

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests tqdm pillow

      - name: Grab thumbnails
        run: |
          python - <<'PY'
import os, json, requests
from PIL import Image
from io import BytesIO
import tqdm

# Folder output
out_dir = "thumbnails"
os.makedirs(out_dir, exist_ok=True)

# Contoh: ganti path dengan file database ikanmu
db_url = "https://raw.githubusercontent.com/deathstrats/Ketikamimpimu/main/all_fishes%20(4).lua"
print(f"Fetching fish database from {db_url}")
r = requests.get(db_url)
data = r.text

# Cari semua assetId di file (sederhana)
import re
asset_ids = re.findall(r"rbxassetid://(\d+)", data)
print(f"Found {len(asset_ids)} asset IDs")

for asset_id in tqdm.tqdm(asset_ids):
    url = f"https://www.roblox.com/asset-thumbnail/image?assetId={asset_id}&width=512&height=512&format=png"
    resp = requests.get(url)
    if resp.status_code == 200:
        img = Image.open(BytesIO(resp.content))
        filename = f"{out_dir}/{asset_id}.png"
        img.save(filename)
    else:
        print(f"Failed to fetch {asset_id}")

print("Download selesai, file disimpan di folder:", out_dir)
PY

      - name: Commit & Push Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add thumbnails || echo "No files found"
          git commit -m "chore: add generated thumbnails [skip ci]" || echo "No changes to commit"
          git push
